// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA41FBMXuXPKaI-wjZ_wv_BWZ-xzv_-_Xo',
    appId: '1:326253516949:web:59205561f1e1a656cba39c',
    messagingSenderId: '326253516949',
    projectId: 'software-86000',
    authDomain: 'software-86000.firebaseapp.com',
    storageBucket: 'software-86000.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9PPg_pr3muLOWyxIZ_CpA3tMczMeRoXY',
    appId: '1:326253516949:android:22326ab0d9122642cba39c',
    messagingSenderId: '326253516949',
    projectId: 'software-86000',
    storageBucket: 'software-86000.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgPYxA6XzfjZW1KvFaz2xRyvajvgm7lIM',
    appId: '1:326253516949:ios:acead6a084f94599cba39c',
    messagingSenderId: '326253516949',
    projectId: 'software-86000',
    storageBucket: 'software-86000.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgPYxA6XzfjZW1KvFaz2xRyvajvgm7lIM',
    appId: '1:326253516949:ios:acead6a084f94599cba39c',
    messagingSenderId: '326253516949',
    projectId: 'software-86000',
    storageBucket: 'software-86000.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA41FBMXuXPKaI-wjZ_wv_BWZ-xzv_-_Xo',
    appId: '1:326253516949:web:5fe1ed2788833118cba39c',
    messagingSenderId: '326253516949',
    projectId: 'software-86000',
    authDomain: 'software-86000.firebaseapp.com',
    storageBucket: 'software-86000.firebasestorage.app',
  );
}
